### ISSUE TITLE
FileNotFoundError： suggest adding a library that excludes indexing

### ISSUE THREAD

**Issue by windily-cloud** [Garulf/Obsidian-Notes#12]
Please type any relevant information here：

This does not seem to be able to index soft links, suggest adding a library that excludes indexing

<details open><summary>Trace Log</summary>
<p>

```
Traceback (most recent call last):
  File "C:\Users\cloud\AppData\Roaming\FlowLauncher\Plugins\Obsidian Notes-1.1.4\lib\flox\launcher.py", line 44, in run
    results = request_method(*request_parameters) or self._results
  File "C:\Users\cloud\AppData\Roaming\FlowLauncher\Plugins\Obsidian Notes-1.1.4\lib\flox\__init__.py", line 131, in _query
    self.query(query)
  File "C:\Users\cloud\AppData\Roaming\FlowLauncher\Plugins\Obsidian Notes-1.1.4\plugin\main.py", line 26, in query
    for note in vault.notes():
  File "C:\Users\cloud\AppData\Roaming\FlowLauncher\Plugins\Obsidian Notes-1.1.4\plugin\obsidian.py", line 62, in notes
    for note in Path(self.path).glob('**/*.md'):
  File "C:\ProgrammingSoftware\Python3.10\lib\pathlib.py", line 1032, in glob
    for p in selector.select_from(self):
  File "C:\ProgrammingSoftware\Python3.10\lib\pathlib.py", line 493, in _select_from
    for p in successor_select(starting_point, is_dir, exists, scandir):
  File "C:\ProgrammingSoftware\Python3.10\lib\pathlib.py", line 440, in _select_from
    with scandir(parent_path) as scandir_it:
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'D:\\Project\\Obsidian\\obsidian-develop\\.obsidian\\plugins\\obsidian-quiet-outline\\node_modules\\.pnpm\\node_modules\\@babel\\helper-validator-identifier'

```
</p>
</details>

**Comment by Garulf** [comment]
Hell @windily-cloud Could you please clarify what you mean by " a library that excludes indexing"?

Also you I *should* be suppressing this error so the whole plugin does not crash. Thanks for making me aware.

**Comment by windily-cloud** [comment]
Thank you for your reply！ At that time I just wanted a setting that would exclude some paths, because my obsidian vault has a  Symbolic Link that could cause the plugin to fail.
