### ISSUE TITLE
Error aftery typing ob:

### ISSUE THREAD

**Issue by quaikohc** [Garulf/Obsidian-Notes#13]
Flow Launcher version: 1.9.5
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 10/19/2022 15:09:31
Exception:
Obsidian Notes Exception: 
Websites: https://github.com/Garulf/obsidian-notes
Author: Garulf
Version: 1.1.4
[2022-10-19.txt](https://github.com/Garulf/Obsidian-Notes/files/9820744/2022-10-19.txt)

Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Obsidian Notes|Traceback (most recent call last):
  File "C:\Users\pw\AppData\Roaming\FlowLauncher\Plugins\Obsidian Notes-1.1.4\run.py", line 9, in <module>
    from plugin.main import Obsidian
ImportError: No module named plugin.main

 ---> System.IO.InvalidDataException: Obsidian Notes|Traceback (most recent call last):
  File "C:\Users\pw\AppData\Roaming\FlowLauncher\Plugins\Obsidian Notes-1.1.4\run.py", line 9, in <module>
    from plugin.main import Obsidian
ImportError: No module named plugin.main

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 288
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 302
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 322
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 626
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 627
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

any ideas?

Cheers

**Comment by Garulf** [comment]
Hello @quaikohc,

Do you have Python installed?

If yes which version?

This error doesn't make any sense as it's saying it can't find the rest of the plugins files in its own directory. It may fix itself with a reinstall.
