### ISSUE TITLE
Unexpected Behaviour

### ISSUE THREAD

**Issue by semanticdata** [Garulf/Obsidian-Notes#15]
Flow Launcher version: 1.10.0
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 12/15/2022 09:38:27
Exception:
Obsidian Notes Exception: 
Websites: https://github.com/Garulf/obsidian-notes
Author: Garulf
Version: 1.1.4
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Cannot access a disposed object.
Object name: 'The stream with Id 6ca408f8-55b0-47b7-915a-069dbe6f3b19 and Tag  is disposed.'.
 ---> System.ObjectDisposedExcept
[2022-12-15.txt](https://github.com/Garulf/Obsidian-Notes/files/10238471/2022-12-15.txt)
ion: Cannot access a disposed object.
Object name: 'The stream with Id 6ca408f8-55b0-47b7-915a-069dbe6f3b19 and Tag  is disposed.'.
   at Microsoft.IO.RecyclableMemoryStream.ThrowDisposedException() in /_/src/RecyclableMemoryStream.cs:line 1444
   at Microsoft.IO.RecyclableMemoryStream.get_Length() in /_/src/RecyclableMemoryStream.cs:line 445
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 283
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 295
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 310
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 190
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 210
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass120_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 730
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 704
[2022-12-15.txt](https://github.com/Garulf/Obsidian-Notes/files/10238451/2022-12-15.txt)

   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Garulf** [comment]
Looks like you're having an issue with Flow Launcher not the Obsidian plugin according to this log. Please create an issue here:
https://github.com/Flow-Launcher/Flow.Launcher/issues/new/choose
