### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by Abod1960** [Garulf/Obsidian-Notes#29]
Please type any relevant information here

it just does not show anything, I have 3 vaults btw...

<details open><summary>Trace Log</summary>
<p>

```
Traceback (most recent call last):
  File "C:\Users\omen\AppData\Roaming\FlowLauncher\Plugins\Obsidian Notes-1.1.4\lib\flox\launcher.py", line 44, in run
    results = request_method(*request_parameters) or self._results
  File "C:\Users\omen\AppData\Roaming\FlowLauncher\Plugins\Obsidian Notes-1.1.4\lib\flox\__init__.py", line 131, in _query
    self.query(query)
  File "C:\Users\omen\AppData\Roaming\FlowLauncher\Plugins\Obsidian Notes-1.1.4\plugin\main.py", line 26, in query
    for note in vault.notes():
  File "C:\Users\omen\AppData\Roaming\FlowLauncher\Plugins\Obsidian Notes-1.1.4\plugin\obsidian.py", line 62, in notes
    for note in Path(self.path).glob('**/*.md'):
  File "pathlib.py", line 1139, in glob
  File "pathlib.py", line 586, in _select_from
  File "pathlib.py", line 533, in _select_from
FileNotFoundError: [WinError 3] The system cannot find the path specified: "H:\\Abod1960 vault - obsidian\\PKM - 2nd Brain\\Notion\\library\\Shelves\\Buying list\\Buying list\\HONEY BEAR Initial Alphabet Letter Silver Cufflinks for Men's Shirt, Stainless Steel for Business Wedding Gift (B-Black)- Buy Online at Best Price in UAE - Amazon.ae"

```
</p>
</details>

**Comment by Garulf** [comment]
Looks like it's crashing when enumerating through this `.ae` file. 

Is your vault part of a cloud storage sync folder?

Some applications like Dropbox have a streaming option that doesn't download a file to your system unless it's accessed. This may be what's going on here.

**Comment by Abod1960** [comment]
> Looks like it's crashing when enumerating through this `.ae` file.
> 
> Is your vault part of a cloud storage sync folder?
> 
> Some applications like Dropbox have a streaming option that doesn't download a file to your system unless it's accessed. This may be what's going on here.

i actually have more than one vault, some are on the cloud but it is not showing any, not the cloud ones and not the local ones...
