### ISSUE TITLE
I get this error message right after typing "ob" (Obsidian Notes: Failed to respond!) 

### ISSUE THREAD

**Issue by matesvecenik** [Garulf/Obsidian-Notes#36]
Hi. New to Flow Launcher, just noticed it has an Obsidian plugin which is amazing. Unfortunately I can't get it to work. Any ideas why? 

Any help would be greatly appreciated. thanks so much in advance! 🙏 

### **Error screenshot:**
![image](https://github.com/Garulf/Obsidian-Notes/assets/171559452/2d9b5b87-1ce3-491e-a563-1093e3aeb7a5)

### **Here is my log file:**
[2024-06-03.txt](https://github.com/user-attachments/files/15531879/2024-06-03.txt)

Flow Launcher version: 1.18.0
OS Version: 22631.3672
IntPtr Length: 8
x64: True

```
Python Path: C:\Users\Marin\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: 
Date: 06/03/2024 11:36:08
Exception:
Obsidian Notes Exception: 
Websites: https://github.com/Garulf/obsidian-notes
Author: Garulf
Version: 1.1.4
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: --- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Marin\AppData\Roaming\FlowLauncher\Plugins\Obsidian Notes-1.1.4\lib\flox\launcher.py", line 44, in run
    results = request_method(*request_parameters) or self._results
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Marin\AppData\Roaming\FlowLauncher\Plugins\Obsidian Notes-1.1.4\lib\flox\__init__.py", line 131, in _query
    self.query(query)
  File "C:\Users\Marin\AppData\Roaming\FlowLauncher\Plugins\Obsidian Notes-1.1.4\plugin\main.py", line 38, in query
    context=[vault.id, str(note.path), note.checklists()]
                                       ^^^^^^^^^^^^^^^^^
  File "C:\Users\Marin\AppData\Roaming\FlowLauncher\Plugins\Obsidian Notes-1.1.4\plugin\obsidian.py", line 106, in checklists
    for line in self.content().splitlines():
                ^^^^^^^^^^^^^^
  File "C:\Users\Marin\AppData\Roaming\FlowLauncher\Plugins\Obsidian Notes-1.1.4\plugin\obsidian.py", line 85, in content
    with open(self.path, 'r', encoding='utf-8', errors='replace') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: "C:\\Users\\Marin\\iCloudDrive\\iCloud~md~obsidian\\Marin's Obsidian\\99 - Meta\\Attachments\\Bezmalinovic\u0301, Alfonso. �Skripta za Voditelja Brodice B Kategorije,� May 2022_.md"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1113, in emit
  File "encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\u0301' in position 166: character maps to <undefined>
Call stack:
  File "C:\Users\Marin\AppData\Roaming\FlowLauncher\Plugins\Obsidian Notes-1.1.4\run.py", line 12, in <module>
    Obsidian()
  File "C:\Users\Marin\AppData\Roaming\FlowLauncher\Plugins\Obsidian Notes-1.1.4\lib\flox\launcher.py", line 16, in __del__
    self.run(debug)
  File "C:\Users\Marin\AppData\Roaming\FlowLauncher\Plugins\Obsidian Notes-1.1.4\lib\flox\launcher.py", line 46, in run
    self.logger.exception(e)
  File "logging\__init__.py", line 1524, in exception
  File "logging\__init__.py", line 1518, in error
  File "logging\__init__.py", line 1634, in _log
  File "logging\__init__.py", line 1644, in handle
  File "logging\__init__.py", line 1706, in callHandlers
  File "logging\__init__.py", line 978, in handle
  File "logging\handlers.py", line 75, in emit
  File "logging\__init__.py", line 1230, in emit
  File "logging\__init__.py", line 1118, in emit
Message: PermissionError(13, 'Permission denied')
Arguments: ()

 ---> System.IO.InvalidDataException: --- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Marin\AppData\Roaming\FlowLauncher\Plugins\Obsidian Notes-1.1.4\lib\flox\launcher.py", line 44, in run
    results = request_method(*request_parameters) or self._results
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Marin\AppData\Roaming\FlowLauncher\Plugins\Obsidian Notes-1.1.4\lib\flox\__init__.py", line 131, in _query
    self.query(query)
  File "C:\Users\Marin\AppData\Roaming\FlowLauncher\Plugins\Obsidian Notes-1.1.4\plugin\main.py", line 38, in query
    context=[vault.id, str(note.path), note.checklists()]
                                       ^^^^^^^^^^^^^^^^^
  File "C:\Users\Marin\AppData\Roaming\FlowLauncher\Plugins\Obsidian Notes-1.1.4\plugin\obsidian.py", line 106, in checklists
    for line in self.content().splitlines():
                ^^^^^^^^^^^^^^
  File "C:\Users\Marin\AppData\Roaming\FlowLauncher\Plugins\Obsidian Notes-1.1.4\plugin\obsidian.py", line 85, in content
    with open(self.path, 'r', encoding='utf-8', errors='replace') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: "C:\\Users\\Marin\\iCloudDrive\\iCloud~md~obsidian\\Marin's Obsidian\\99 - Meta\\Attachments\\Bezmalinovic\u0301, Alfonso. �Skripta za Voditelja Brodice B Kategorije,� May 2022_.md"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1113, in emit
  File "encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\u0301' in position 166: character maps to <undefined>
Call stack:
  File "C:\Users\Marin\AppData\Roaming\FlowLauncher\Plugins\Obsidian Notes-1.1.4\run.py", line 12, in <module>
    Obsidian()
  File "C:\Users\Marin\AppData\Roaming\FlowLauncher\Plugins\Obsidian Notes-1.1.4\lib\flox\launcher.py", line 16, in __del__
    self.run(debug)
  File "C:\Users\Marin\AppData\Roaming\FlowLauncher\Plugins\Obsidian Notes-1.1.4\lib\flox\launcher.py", line 46, in run
    self.logger.exception(e)
  File "logging\__init__.py", line 1524, in exception
  File "logging\__init__.py", line 1518, in error
  File "logging\__init__.py", line 1634, in _log
  File "logging\__init__.py", line 1644, in handle
  File "logging\__init__.py", line 1706, in callHandlers
  File "logging\__init__.py", line 978, in handle
  File "logging\handlers.py", line 75, in emit
  File "logging\__init__.py", line 1230, in emit
  File "logging\__init__.py", line 1118, in emit
Message: PermissionError(13, 'Permission denied')
Arguments: ()

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 243
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 248
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 261
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 196
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 195
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_1.<QueryForPluginAsync>b__1(ActionContext _) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 224
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 246
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 307
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by Garulf** [comment]
Hello @matesvecenik , sorry to see you’re having an issue with the plugin. 

According to the log it looks like it has some sort of permission issue with one or more files in your vault. Please double check the appropriate permissions are set for your vault.

**Comment by MelodyDuplaix** [comment]
Hello, I have the same problem, and I think the same error. What do you mean by "check the appropriate permissions are set for your vault" please ?

**Comment by MelodyDuplaix** [comment]
Actually it's good, I found, it's because I had a .sync folder in my trunk, as well as files with bad names (like $.md) in the .trash
