### ISSUE TITLE
Not working on install.

### ISSUE THREAD

**Issue by AlanEdd** [Garulf/Obsidian-Notes#39]
Here is the exception message and the log.
I would appreciate any pointers. I didn't into any of the functionality on the first launch.
Thank you.

[2024-07-29.txt](https://github.com/user-attachments/files/16411833/2024-07-29.txt)
`Flow Launcher version: 1.18.0

OS Version: 19045.4651
IntPtr Length: 8
x64: True

Python Path: C:\Users\eddiea\Programs\FlowSearch\app-1.18.0\UserData\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: 
Date: 07/29/2024 12:19:51
Exception:
Obsidian Notes Exception: 
Websites: https://github.com/Garulf/obsidian-notes
Author: Garulf
Version: 1.1.4
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "C:\Users\eddiea\Programs\FlowSearch\app-1.18.0\UserData\Plugins\Obsidian Notes-1.1.4\run.py", line 9, in <module>
    from plugin.main import Obsidian
  File "C:\Users\eddiea\Programs\FlowSearch\app-1.18.0\UserData\Plugins\Obsidian Notes-1.1.4\plugin\main.py", line 3, in <module>
    from flox import Flox
  File "C:\Users\eddiea\Programs\FlowSearch\app-1.18.0\UserData\Plugins\Obsidian Notes-1.1.4\lib\flox\__init__.py", line 46, in <module>
    raise FileNotFoundError("Unable to locate Launcher directory")
FileNotFoundError: Unable to locate Launcher directory

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\eddiea\Programs\FlowSearch\app-1.18.0\UserData\Plugins\Obsidian Notes-1.1.4\run.py", line 9, in <module>
    from plugin.main import Obsidian
  File "C:\Users\eddiea\Programs\FlowSearch\app-1.18.0\UserData\Plugins\Obsidian Notes-1.1.4\plugin\main.py", line 3, in <module>
    from flox import Flox
  File "C:\Users\eddiea\Programs\FlowSearch\app-1.18.0\UserData\Plugins\Obsidian Notes-1.1.4\lib\flox\__init__.py", line 46, in <module>
    raise FileNotFoundError("Unable to locate Launcher directory")
FileNotFoundError: Unable to locate Launcher directory

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 243
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 248
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 261
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 196
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 230
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_1.<QueryForPluginAsync>b__1(ActionContext _) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 224
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 246
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 307
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
`

**Comment by Garulf** [comment]
This plugin does not support custom install locations. Please rename your Flow Launcher installation directory to "FlowLauncher".

**Comment by AlanEdd** [comment]
Wonderful, thanks so much for that. I should have realised myself.

**Comment by Garulf** [comment]
> Wonderful, thanks so much for that. I should have realised myself.

No problem, this plugin uses old code to be backwards compatible with Wox. Updated versions should not have this limitation as Wox support is being removed (slowly) from all my plugins.
